/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityScanPopup: (typeof import('./src/components/activityScanPopup.vue'))['default'];
    AuthModule: (typeof import('./src/components/authModule.vue'))['default'];
    Container: (typeof import('./src/components/container.vue'))['default'];
    CopySuccess: (typeof import('./src/components/copySuccess.vue'))['default'];
    Empty: (typeof import('./src/components/empty.vue'))['default'];
    Popup: (typeof import('./src/components/popup.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    ScanCodeModule: (typeof import('./src/components/scanCodeModule.vue'))['default'];
    TabBar: (typeof import('./src/components/tabBar.vue'))['default'];
    UnAuthorized: (typeof import('./src/components/unAuthorized.vue'))['default'];
  }
}
